[build.environment]
	NODE_VERSION = "22"

[build]
	publish = ".vitepress/dist"
	command = "pnpm run build"

[dev]
	command = "pnpm run dev"
	targetPort = 5173
	autoLaunch = false
	framework = "#custom"


# generated redirects from '_redirects' file
# (delete to the end of the file and append this output)
# grep '^[^#]' _redirects | awk '{print "\n[[redirects]]\nfrom = \""$1"\"\nto   = \""$2"\""}'

[[redirects]]
from = "/*"
to   = "https://directus.io/docs/"
